version: 2

sources:
  - name: staging
    database: dtc-de-course-448111
    schema: zoomcamp
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: external_fhv_2019